/* this file automatically generated by the Makefile */
#define COMPILER "gcc -std=c99 -D_GNU_SOURCE -m64"
#define OPTIMIZE "-O3"
#define CFLAGS   "-D__USE_FIXED_PROTOTYPES__ -O3"
#define OBJDIR   "obj"
